version: '3'

services:
  backend:
    build: ./
    volumes:
      - ./timeSeriesImputerParameterizer:/app
      - ./Dataset_Categorizer:/app/Dataset_Categorizer
      - ./Datasets:/Datasets
      - ./IIM:/app/IIM
      - ./M_RNN:/app/M_RNN
      - ./MRNN:/app/MRNN
      - ./Optimizer:/Optimizer
      - ./Results:/Results
      - ./Utils_Thesis:/app/Utils_Thesis
      - ./Wrapper:/app/Wrapper

      - ./Optimizer:/app/Optimizer
      - ./Results:/app/Results
      - ./Datasets:/app/Datasets


    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=timeSeriesImputerParameterizer.settings

  frontend:
    build: ./parameterizer_frontend
    volumes:
      - ./parameterizer_frontend:/app
      - /parameterizer_frontend/app/node_modules
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
