version: '3'
# TODO This does not work yet
services:
  backend:
    build: ./
    command: /start_backend.sh
    volumes:
      - ./timeSeriesImputerParameterizer:/app
      - ./Dataset_Categorizer:/app/Dataset_Categorizer
      - ./Datasets:/app/Datasets
      - ./IIM:/app/IIM
      - ./M_RNN:/app/M_RNN
      - ./MRNN:/app/MRNN
      - ./Optimizer:/app/Optimizer
      - ./Utils_Thesis:/app/Utils_Thesis
      - ./Wrapper:/app/Wrapper
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=timeSeriesImputerParameterizer.settings

  frontend:
    build: ./parameterizer_frontend
    command: /start_frontend.sh
    volumes:
      - ./parameterizer_frontend:/app
      - /parameterizer_frontend/app/node_modules
      - .:/usr/src/app
      - /usr/src/app/node_modules

    ports:
      - "8080:8080"
